### PR TITLE
Add command line arguments to environment collection

### PR DESCRIPTION
**Pull request by uber-rob**
Slightly interesting for IIS-hosted projects but pretty much essential for console apps.

I would have thought that this could be redacted as per usual if users have confidential information on the command line (meep) but if you think logging command line argument should be an option on the logger I can add that functionality and document accordingly. I'd have it enabled by default so that users get full functionality by default - but again will work to your spec.

I've added a test console app to the project as well.

### CODE REVIEW

**Comment by uber-rob** [comment]
Any thoughts on this by the way? Would love to get it in the package.

**Comment by rogersillito** [comment]
Ok I've run through it all - it's essentially a fairly simple addition (which I can see being useful for me in the near future).  The error handling around `GetCommandLineArgs()` ought to gracefully deal with any cases where these aren't available.  For absolute peace of mind I'd like to be able to see it running when the exception does get thrown, but ultimately [it's the only exception that can throw](https://msdn.microsoft.com/en-us/library/system.environment.getcommandlineargs%28v=vs.110%29.aspx), so in my view the option to enable support for this shouldn't be necessary.

I'll add some command line args into your test project's Start Options so these get captured when running in the visual studio debugger.

As an aside, do you know what the DSNs that feature in these test harness projects actually point to?  I get a login prompt when I visit http://app.getsentry.com/3739 (from your console test project).   It's obviously easy to re-point to a sentry install where you do have access though.  [Looks like this sort of question has come up elsewhere already](https://github.com/damiencaselli/ember-cli-sentry/issues/21).

**Comment by uber-rob** [comment]
Good news! I'll look out for the new package.

I have no idea about the DSN in the repo (I think I tested against one of our projects because that's what I would do - but it was two weeks ago now so I don't remember for sure), I presume someone, somewhere is getting some new alerts but they've not chosen to regenerate their keys or anything so they must be OK with that.

Thanks again for accepting the PR :)

**Comment by rogersillito** [comment]
No problem - I've just submitted the updated package.

**Pull request merged**
